export const environment = {
  production: true,
  contentful: {
    spaceID: "b73d407c7z3q",
    token: "173bbb7627a7cdc82292e2a99d28d5004612fbc724a4e74a643629c67d98919f",
    categoryIDs: {
      news: "4bGp5zRaVOAmO2gaMuagEO",
      jumbotron: "28BCNlBF6Msggwa2ECkokm",
      showdown: "4ppO2xYoPHCmRmEGaQMFDF",
      nexusEdge: "dlyJJ9HDiQry7cjYFb6VX",
      podcast: "5tANSA3t3WNrFtzsCl5Wnp",
    },
  },
  s3bucketImages: "ngs-image-storage",
  s3bucketReplays: "ngs-replay-storage",
  s3bucketGeneralImage: "ngs-general-image",
  s3bucketArchiveImage: "ngs-archive-image",
  awsTld: "https://s3.amazonaws.com/",
  socketURL: "https://www.nexusgamingseries.org",
  heroesProfilePlayer: "https://www.heroesprofile.com/NGS/Profile/?",
  heroesProfile: "https://www.heroesprofile.com/Profile/?",
  heroesProfileTeam: "https://heroesprofile.com/NGS/Team/Single/?team=",
  season: 7,
  seasonStart: 1562572800000,
};
